INSERT INTO `mydb`.`competence` (`name`, `level`, `reward`) VALUES ('Electronique', '0', '0');
INSERT INTO `mydb`.`competence` (`name`, `level`, `reward`) VALUES ('Couture', '0', '0');
INSERT INTO `mydb`.`competence` (`name`, `level`, `reward`) VALUES ('Mécanique', '0', '0');
INSERT INTO `mydb`.`competence` (`name`, `level`, `reward`) VALUES ('Programmation', '0', '0');
INSERT INTO `mydb`.`competence` (`name`, `level`, `reward`) VALUES ('Ebénisterie', '0', '0');


INSERT INTO `mydb`.`machine` (`name`, `pseudo`, `description`, `url_photo`, `video_link`, `notice`, `discord_link` ) VALUES ('LASER-SP100', 'Albert', 'Découpe Laser : Trotec Speedy 100\nPuissance du laser : 60 watts\nSurface de travail : 610mm x 305mm\nÉpaisseur Max : 10mm\nMatériaux usinables:\n\nGravure : bois (sauf mdf), carton, plexiglas (acrylique), textile, pierre, verre, cuir\nDécoupe : bois (sauf mdf), carton, plexiglas (acrylique), textile, papier, cuir', 'https://artilect.fr/wp-content/uploads/doliconnect/product/183/LASER-SP100-Plan%20de%20travail%2080-200x200.png', 'https://www.youtube.com/watch?v=bdLReN9phgg&ab_channel=SeeSamSolutions', 'https://lesatelierseclaires-manager.com/uploads/machine_file/37/LASER_mode-d-emploi_version-PRINT_2016-10-01.pdf', 'https://discord.gg/Dmhgk8AT');
INSERT INTO `mydb`.`machine` (`name`, `pseudo`, `description`, `url_photo`, `video_link`, `notice`, `discord_link` ) VALUES ('PRINT-CAMM1 ', 'Cathy', 'Course : 50-700 mm\nPassage sous portique : 165mm\nMatériaux : vinyle,  papier,vinyles, flocages, matériaux de transfert, adhésifs de fenêtre\nApplications : lettrage, transferts pour vêtements,  prototypes d’emballage, signalisation et les Course : 50-700 mm\nPassage sous portique : 165mm\nMatériaux : vinyle,  papier,vinyles, flocages, matériaux de transfert, adhésifs de fenêtre\nApplications : lettrage, transferts pour vêtements,  prototypes d’emballage, signalisation et les autocollants... La découpe vinyle permet de découper des habillages de véhicule, des panneaux signalétiques, des stickers, des textiles décorés et autres créations graphiques.', 'https://artilect.fr/wp-content/uploads/doliconnect/product/37/PRINT-CAMM1-Plan%20de%20travail%2082-200x200.png', 'https://www.youtube.com/watch?v=AMBFQtDi5o0&ab_channel=RolandDGCentralEurope', 'https://www.machines-3d.com/images/Image/File/notice/Manuel_utilisation_FR_GS24.pdf', 'https://discord.gg/ZrurkTR8');
INSERT INTO `mydb`.`machine` (`name`, `pseudo`, `description`, `url_photo`, `video_link`, `notice`, `discord_link` ) VALUES ('UV-LEF200', 'Roland', 'Impression UV : LEF 2 200\nSurface de travail : 508mmx330mm\nÉpaisseur Max : 10mm\n\nTarification au volume d\'encre consommée (ML)\nA titre indicatif : la surface maximale (508x330mm) revient à 15€ ou un format A4 (210x297mm) revient à 6€. L’impression UV offre les meilleures possibilités en matière de personnalisation et de création d’objets customisés : cadeaux, gadgets, appareils électroniques, céramiques, accessoires de mode, enseignes et objets de décoration intérieure…', 'https://artilect.fr/wp-content/uploads/doliconnect/product/245/UV-LEF200-Plan%20de%20travail%2094-200x200.png', 'https://www.youtube.com/watch?v=hrkL2zOOP34', 'https://webmanual.rolanddg.com/contents/manuals/LEF-200_STA_EN_R3.pdf', 'https://discord.gg/ZrurkTR8');
INSERT INTO `mydb`.`machine` (`name`, `pseudo`, `description`, `url_photo`, `video_link`, `notice`, `discord_link` ) VALUES ('FAB-ENDER1', 'Fabio', 'Couleur de matériau disponible : blanc, rouge, bleu, noir, vert et jaune\nÉpaisseur de couche minimale : 0.10mm\nTaille d’impression : 220x220x250mm\nFormat d’entrée : STL, GCODE, OBJ\nMatériau d’impression : PLA. Les imprimantes 3D permettent de produire des objets réels de tout type à partir d’un fichier 3D. Les matières disponibles sont des dérivées plastiques ou assimilés et existent dans de nombreuses couleurs.', 'https://artilect.fr/wp-content/uploads/doliconnect/product/224/FAB-ENDER1-Plan%20de%20travail%2088-200x200.png', 'https://www.youtube.com/watch?v=8chl5VqQkSs', 'https://www.lesimprimantes3d.fr/wp-content/uploads/2018/10/Ender3-QuickStart.pdf', 'https://discord.gg/ZrurkTR8');
INSERT INTO `mydb`.`machine` (`name`, `pseudo`, `description`, `url_photo`, `video_link`, `notice`, `discord_link` ) VALUES ('LASER-SP500', 'Norbert', 'Découpe Laser : Trotec Speedy 500\nPuissance du laser : 120 watts\nSurface de travail : 1245mm x 710mm\nÉpaisseur Max : 10mm\nCharge matière max. : 25kg\nMatériaux usinables:\n\nGravure : bois (sauf mdf), carton, plexiglas (acrylique), textile, pierre, verre, cuir\nDécoupe : bois (sauf mdf), carton, plexiglas (acrylique), textile, papier, cuir', 'https://artilect.fr/wp-content/uploads/doliconnect/product/8/LASER-SP500-Plan%20de%20travail%2079-200x200.png', 'https://www.youtube.com/watch?v=F6iQF935y4w&ab_channel=TrotecLaser', 'https://www.troteclaser.com/fileadmin/content/images/Contact_Support/Manuals/8014-SP500-Manual-EN.pdf', 'https://discord.gg/ZrurkTR8');


INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('1', '1');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('4', '1');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('4', '2');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('4', '3');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('4', '4');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('1', '5');
INSERT INTO `mydb`.`competence_machine` (`fk_competence_id`, `fk_machine_id`) VALUES ('4', '5');

INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Raquette de ping-pong', 'En cours', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://lab.flers-agglo.fr/uploads/project_image/329/large_project_image.jpg', '1');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Afficheur CO2', 'Terminé', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://edulab.univ-rennes2.fr/uploads/project_image/929/large_project_image.png', '5');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Création de plaque de plastique', 'En cours', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://fabmanager.simplon.co/uploads/project_image/787/large_project_image.jpg', '1');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Tampon de blagues scientifiques', 'Terminé', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://fablab.ledome.info/uploads/project_image/2483/large_project_image.jpg', '4');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Tuile sur tulle', 'En cours', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://fabmanager.simplon.co/uploads/project_image/719/large_project_image.jpg', '4');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Réalisation de Tote Bag', 'Terminé', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://artifab.cmar-paca.fr/uploads/project_image/121/large_project_image.jpg', '2');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Décoration de noël en découpe', 'En cours', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://edulab.univ-rennes2.fr/uploads/project_image/926/large_project_image.jpg', '5');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Masque imprimé', 'Terminé', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://fablab-emode.fr/uploads/project_image/115/large_project_image.jpg', '2');
INSERT INTO `mydb`.`project` (`name`, `status`, `description`, `discord_link`, `image`, `fk_machine_id`) VALUES ('Logo pour poubelle recyclage', 'Terminé', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'https://discord.gg/agA2DapU', 'https://fablab.ledome.info/uploads/project_image/2086/large_project_image.jpeg', '2');

INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('1', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('1', '5');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('2', '1');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('2', '3');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('2', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('2', '5');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('3', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('4', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('4', '5');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('5', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('6', '2');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('6', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('7', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('7', '5');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('8', '2');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('8', '4');
INSERT INTO `mydb`.`project_competence` (`fk_project_id`, `fk_competence_id`) VALUES ('9', '4');
